### ISSUE TITLE
empty text objects cause segfaults

### ISSUE THREAD

**Issue by jsleeio** [gmlewis/go-gerber#8]
**Describe the bug**

reproducible segfault in `gerber.Gerber.WriteGerber` if empty text objects are included.

* if text supplied: no segfault
* if only whitespace supplied: no segfault
* if empty string supplied: segfault

**To Reproduce**

The below code reproduces the issue. If text is supplied via the `-text` flag, should have no segfault.

```
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/gmlewis/go-fonts/fonts"
	_ "github.com/gmlewis/go-fonts/fonts/bitstreamverasansmono_bold"
	"github.com/gmlewis/go-gerber/gerber"
)

func main() {
	var text string
	flag.StringVar(&text, "text", "", "text to render on the panel")
	flag.Parse()
	g := gerber.New("textbug")
	g.TopSilkscreen().Add(
		gerber.Text(
			25, 25,
			1.0,    // for top silk
			text,
			"bitstreamverasansmono_bold",
			12,
			&gerber.TextOpts{XAlign: fonts.XCenter, YAlign: fonts.YCenter},
		),
	)
	if err := g.WriteGerber(); err != nil {
		fmt.Printf("write: %v", err)
		os.Exit(1)
	}
}
```

**Expected behavior**

`gerber.Text` API does not return errors, so perhaps log a warning instead? Not really sure what's best here.

**Screenshots**
```$ ./gerber-empty-text-bug -text=
$ go build && rm -f textbug.* && ./gerber-empty-text-bug -text='' && gerbv textbug*
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x102be9270]

goroutine 1 [running]:
github.com/gmlewis/go-fonts/fonts.TextMBB(0x4039000000000000, 0x4039000000000000, 0x4010eeeeeeeeeeef, 0x4010eeeeeeeeeeef, {0x16d4139e9, 0x0}, {0x102bf9091?, 0x1029f54cc?})
	/Users/jslee/go/pkg/mod/github.com/gmlewis/go-fonts@v0.0.10/fonts/text.go:196 +0x2a0
github.com/gmlewis/go-fonts/fonts.Text(0x4039000000000000, 0x4039000000000000, 0x4010eeeeeeeeeeef, 0x4010eeeeeeeeeeef, {0x16d4139e9, 0x0}, {0x102bf9091, 0x1a}, 0x14000126078)
	/Users/jslee/go/pkg/mod/github.com/gmlewis/go-fonts@v0.0.10/fonts/text.go:221 +0x7c
github.com/gmlewis/go-gerber/gerber.(*TextT).renderText(0x140001009b0)
	/Users/jslee/go/pkg/mod/github.com/gmlewis/go-gerber@v0.0.2/gerber/text.go:109 +0x64
github.com/gmlewis/go-gerber/gerber.(*TextT).WriteGerber(0x140001009b0, {0x102ccd5c8, 0x14000100a00}, 0x7?)
	/Users/jslee/go/pkg/mod/github.com/gmlewis/go-gerber@v0.0.2/gerber/text.go:143 +0x2c
github.com/gmlewis/go-gerber/gerber.(*Layer).WriteGerber(0x140003685a0, {0x102ccd5c8, 0x14000100a00})
	/Users/jslee/go/pkg/mod/github.com/gmlewis/go-gerber@v0.0.2/gerber/layers.go:56 +0x220
github.com/gmlewis/go-gerber/gerber.(*Gerber).WriteGerber(0x14000141f30)
	/Users/jslee/go/pkg/mod/github.com/gmlewis/go-gerber@v0.0.2/gerber/gerber.go:43 +0x1bc
main.main()
	/Users/jslee/vc/jsleeio/experiments/gerber/gerber-empty-text-bug/main.go:28 +0x358
```

**Additional context**
Am using macOS and Go 1.19.4. Also reproduced on Linux.

Thanks for making this library; it solved a problem for me :-)

**Comment by gmlewis** [comment]
Thank you for the bug report, @jsleeio !
The latest version [0.0.3](https://github.com/gmlewis/go-gerber/releases/tag/v0.0.3) changes the panic into a fatal error:

```
2023/01/21 08:14:52 MBB (message="",fontName="freeserif"): message must not be empty
```

I first attempted to propagate errors throughout the rendering code, and it led to disaster, so I figure the hard stop is better than a panic. :smile:

Thanks again, and glad you found it useful!
